phaedrus: phaedrus1.md
	../scr.pl phaedrus1.md | pandoc -f markdown-smart -o out.html -s --css ../tufte/tufte.css && perl -pe 's/<img src/<img width="90" height="90" src/g' out.html > phaedrus1.html && rm out.html
